### ISSUE TITLE
Instructions on loading SARIT data?

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/sarit#41]
It would be great if the README.md file could provide instructions for loading the data from https://github.com/eXistSolutions/sarit-data.

**Comment by jensopetersen** [comment]
I think we have to reconsider whether a separate download app is needed. The reason for having this was to ensure that xml:ids were put on all block-level elements and that they were unique throughout the database, but this is no longer required (after 5320c31139fed3b3d9032195483bd3ad8fdef8f8)  and it should be possible to upload the files at https://github.com/sarit/SARIT-corpus without further processing. The xml:ids in the files at https://github.com/sarit/SARIT-corpus should be unique.

**Comment by joewiz** [comment]
Oh, that's nice you can use the source repository now. Perhaps then, some instructions pointing people to the recommended source would be all that's needed. 

I looked at this sarit app again today because I was thinking of creating a similar app for the TCP texts recently announced on TEI-L (http://markmail.org/message/erawv5ioasjtxvki) - allowing you to browse the titles of available texts and make a selection for download, view, query, etc. It's an enormous corpus, so it would be important to guide people in loading their own selection of texts.

**Comment by jensopetersen** [comment]
@wolfgangmm and I also thought we could perhaps expand the SARIT app to accommodate TEI Simple.

**Comment by jensopetersen** [comment]
I have updated the data files in sarit-data and the README now points to the sarit-data repo.
